//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilStationDemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OSMSEntities : DbContext
    {
        public OSMSEntities()
            : base("name=OSMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Approver> Approver { get; set; }
        public virtual DbSet<Entry> Entry { get; set; }
        public virtual DbSet<Job> Job { get; set; }
        public virtual DbSet<LeaveOffice> LeaveOffice { get; set; }
        public virtual DbSet<OilMaterialOrder> OilMaterialOrder { get; set; }
        public virtual DbSet<OilMaterialOrderDetail> OilMaterialOrderDetail { get; set; }
        public virtual DbSet<OrganizationStructure> OrganizationStructure { get; set; }
        public virtual DbSet<ProcessItem> ProcessItem { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<SystemResourceModule> SystemResourceModule { get; set; }
        public virtual DbSet<ProcessStepRecord> ProcessStepRecord { get; set; }
        public virtual DbSet<RoleResourceModule> RoleResourceModule { get; set; }
        public virtual DbSet<StaffRole> StaffRole { get; set; }
        public virtual DbSet<v_staffmune> v_staffmune { get; set; }
        public virtual DbSet<v_Organization> v_Organization { get; set; }
    
        public virtual int P_Pager(ObjectParameter recordTotal, string viewName, string fieldName, string keyName, Nullable<int> pageSize, Nullable<int> pageNo, string orderString, string whereString)
        {
            var viewNameParameter = viewName != null ?
                new ObjectParameter("viewName", viewName) :
                new ObjectParameter("viewName", typeof(string));
    
            var fieldNameParameter = fieldName != null ?
                new ObjectParameter("fieldName", fieldName) :
                new ObjectParameter("fieldName", typeof(string));
    
            var keyNameParameter = keyName != null ?
                new ObjectParameter("keyName", keyName) :
                new ObjectParameter("keyName", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("pageSize", pageSize) :
                new ObjectParameter("pageSize", typeof(int));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("pageNo", pageNo) :
                new ObjectParameter("pageNo", typeof(int));
    
            var orderStringParameter = orderString != null ?
                new ObjectParameter("orderString", orderString) :
                new ObjectParameter("orderString", typeof(string));
    
            var whereStringParameter = whereString != null ?
                new ObjectParameter("whereString", whereString) :
                new ObjectParameter("whereString", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Pager", recordTotal, viewNameParameter, fieldNameParameter, keyNameParameter, pageSizeParameter, pageNoParameter, orderStringParameter, whereStringParameter);
        }
    }
}
